"""Base generator and shared utilities."""
from __future__ import annotations

from abc import ABC, abstractmethod

import yaml

from ..models.generation import GenerationRequest, GenerationResult
from ..models.platform import Platform


class BaseGenerator(ABC):
    @abstractmethod
    def generate(self, request: GenerationRequest, result: GenerationResult) -> None:
        """Write files into the GenerationResult."""


def dump_yaml(data: dict | list) -> str:
    return yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)


def k8s_metadata(name: str, namespace: str | None = None, labels: dict | None = None, annotations: dict | None = None) -> dict:
    meta: dict = {"name": name}
    if namespace:
        meta["namespace"] = namespace
    if labels:
        meta["labels"] = labels
    if annotations:
        meta["annotations"] = annotations
    return meta


def render_root_readme(platform: Platform) -> str:
    cluster_names = ", ".join(c.name for c in platform.clusters)
    env_list = "\n".join(f"- `{e}`" for e in platform.environments)
    assumption_list = "\n".join(f"- {a}" for a in platform.assumptions) or "- None"

    return f"""# {platform.name}

{platform.description or 'Generated by KubeBlueprint.'}

## Platform Overview

| Property | Value |
|---|---|
| Clusters | {cluster_names} |
| GitOps Tool | {platform.gitops_tool} |
| Environments | {", ".join(platform.environments)} |

## Repository Structure

```
k8s/               Kubernetes manifests (base + overlays)
helm/              Helm charts and values
argo-cd/           Argo CD application definitions
terraform/         Infrastructure-as-Code
observability/     Monitoring, dashboards, alerts
environments/      Per-environment configuration overlays
policies/          Network and admission policies
scripts/           Utility scripts
tests/             Smoke tests
docs/              Additional documentation
```

## Environments

{env_list}

## Quick Start

### Prerequisites
- kubectl + access to the cluster
- helm 3.x
- terraform 1.x (for infrastructure)
- argocd CLI (for GitOps)

### Deploy with Argo CD

```bash
# Bootstrap Argo CD
kubectl apply -k argo-cd/bootstrap/

# Apply the root App-of-Apps
kubectl apply -f argo-cd/apps/root-app.yaml
```

### Apply Kubernetes manifests directly

```bash
kubectl apply -k k8s/overlays/dev
kubectl apply -k k8s/overlays/staging
kubectl apply -k k8s/overlays/prod
```

### Terraform infrastructure

```bash
cd terraform
terraform init
terraform workspace new dev
terraform apply -var-file=environments/dev.tfvars
```

## Architecture Assumptions

{assumption_list}

## Security Notes

- Secrets are defined as placeholders. Integrate with External Secrets Operator or Vault before deploying.
- Network policies default to deny-all. Adjust `policies/` for your access requirements.
- TLS is expected on all Ingress resources. Configure cert-manager or provide pre-existing certificates.

## Rollback Strategy

```bash
# Rollback via Argo CD
argocd app rollback <app-name> <revision>

# Rollback via Helm
helm rollback <release-name> <revision>

# Manual rollback via kubectl
kubectl rollout undo deployment/<name> -n <namespace>
```

## GitOps Workflow

1. Commit changes to this repository.
2. Argo CD detects the change and syncs the affected Application.
3. Monitor sync status in the Argo CD UI or via `argocd app get <name>`.

---
*Generated by [KubeBlueprint](https://github.com/your-org/kubeblueprint)*
"""
